springdoc:
  api-docs:
    path: /payment-openapi
    
spring:
  jackson.serialization.indent_output: true
  application:
    name: iss-payment-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres123}
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
    jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
          auto-add-partitions: true # (*) all services create topic and add partitions
          min-partition-count: 2    # (*)         
        bindings:
          input:
             consumer: 
                auto-commit-offset: false
                ack-each-record: true
      bindings:
        input:
          destination: policy-topic
          content-type: application/json # it's redundant here, 'application/json' is the default
          group: eventServiceGroup

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'